# Generated by Django 4.2.16 on 2024-10-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_userprofile_age_alter_userprofile_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='url_file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
