# Generated by Django 4.2.16 on 2024-10-21 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_scrapeddata_url_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='task',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.task'),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='url_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
